javascript-consturctors - Jared Jenvey
JCJenvey/m2-0323-code-solutions pull request #4
Opened 2023-03-22 04:26 UTC by JCJenvey

![javascript-constructors1](https://user-images.githubusercontent.com/64106926/226801973-ecadacc6-4fbc-4084-8ee0-4e44b5d08309.png)
![javascript-constructors2](https://user-images.githubusercontent.com/64106926/226801979-d0b542d7-839e-4edc-8898-8aebaf95dfe2.png)
![javascript-constructors3](https://user-images.githubusercontent.com/64106926/226801990-a991fea7-10f8-4380-bfb4-334ff0a8d5e1.png)

2023-03-22 04:36 UTC, scrumptiousdev requested changes

2023-03-22 04:36 UTC, scrumptiousdev commented on javascript-constructors/example-constructor.js
> +console.log('typeof of ExampleConstructor: ', typeof ExampleConstructor);
Actually we want to console log value and type of `prototype` property of `ExampleConstructor`

2023-03-22 23:29 UTC, JCJenvey commented
![javascript-constructors2(fix)](https://user-images.githubusercontent.com/64106926/227061398-8daf91c8-1957-42e3-9e0a-0e0c2b86b7ec.png)

2023-03-23 05:04 UTC, scrumptiousdev approved these changes
Approved! :)

2023-03-24 01:13 UTC, merged